# .streamlit/secrets.toml


# IMPORTANT:
# 1. Replace MY_AIRTABLE_API_KEY_HERE with NEWLY GENERATED Airtable Personal Access Token (starts with 'pat_').
# 2. Replace MY_AIRTABLE_BASE_ID_HERE with Airtable Base ID (starts with 'app_').
[airtable]
api_key = "patBwkcwvxNkYCdzQ"
base_id = "apprSqQGEZIMMrpSD"
