# .streamlit/secrets.toml

# --- Airtable Credentials ---
# IMPORTANT:
# 1. Replace YOUR_AIRTABLE_API_KEY_HERE with your NEWLY GENERATED Airtable Personal Access Token (starts with 'pat_').
# 2. Replace YOUR_AIRTABLE_BASE_ID_HERE with your Airtable Base ID (starts with 'app_').
[airtable]
api_key = "patBwkcwvxNkYCdzQ.c2185e1afa5990865a33f02cb97f27240082f878faa362897abc819f96d964e6"
base_id = "apprSqQGEZIMMrpSD."
